### ISSUE TITLE
Run Phalcon application from workspace

### ISSUE THREAD

**Issue by robinbertram** [phalcongelist/phaldock#1]
If I enter the `workspace` container and try to run a Phalcon application it returns the following error:

```
PHP Fatal error:  Uncaught Error: Class 'Phalcon\Di' not found in /var/www/phalcon/app/x.php:37
```

Which basically means that Phalcon isn't loaded. To be sure I added `phalcon/incubator` to Composer as it requires Phalcon to run, and it also returned an error.

**Comment by zyxep** [comment]
Hi @rbertram 

I will take a look at it.

**Comment by zyxep** [comment]
This is fixed in commits

e2ccb09682aa639929cc50e2266cd8cec5d6bdea
8bb57fad3f390bd128b3b5b65462fd75367f2cd8

It will run php 7.0.8 with Phalcon 3.0.0 as default
